export const data = [
  { rank: 1, team_name: "Rinca", score: 100, position: "Up", grade: "A" },
  { rank: 2, team_name: "Sekudu", score: 100, position: "Up", grade: "A" },
  { rank: 3, team_name: "Seraya", score: 100, position: "Up", grade: "A" },
  { rank: 4, team_name: "Andros", score: 100, position: "Up", grade: "A" },
  { rank: 5, team_name: "Atlasof", score: 100, position: "Up", grade: "A" },
  {
    rank: 6,
    team_name: "Chesterfield",
    score: 100,
    position: "Up",
    grade: "A",
  },
  { rank: 7, team_name: "Chiloe", score: 100, position: "Up", grade: "A" },
  { rank: 8, team_name: "Comino", score: 100, position: "Up", grade: "A" },
  { rank: 9, team_name: "Majorca", score: 100, position: "Up", grade: "A" },
  { rank: 10, team_name: "Malakula", score: 100, position: "Up", grade: "A" },
  { rank: 11, team_name: "Okinawa", score: 100, position: "Up", grade: "A" },
  { rank: 12, team_name: "Pombo", score: 100, position: "Up", grade: "A" },
  { rank: 13, team_name: "Rugen", score: 100, position: "Down", grade: "A" },
  { rank: 14, team_name: "Rottnest", score: 100, position: "Down", grade: "A" },
  { rank: 15, team_name: "Seymour", score: 100, position: "Up", grade: "A" },
  { rank: 16, team_name: "Frisian", score: 99, position: "Up", grade: "A" },
  { rank: 17, team_name: "Linosa", score: 99, position: "Up", grade: "A" },
  {
    rank: 18,
    team_name: "Montecristo",
    score: 99,
    position: "Down",
    grade: "A",
  },
  { rank: 19, team_name: "Seychelles", score: 99, position: "Up", grade: "A" },
  { rank: 20, team_name: "Borneo", score: 99, position: "Up", grade: "A" },
  { rank: 21, team_name: "Syros", score: 99, position: "Up", grade: "A" },
  { rank: 22, team_name: "Crozet", score: 99, position: "Down", grade: "A" },
  { rank: 23, team_name: "Malta", score: 99, position: "Up", grade: "A" },
  { rank: 24, team_name: "Marajo", score: 99, position: "Up", grade: "A" },
  { rank: 25, team_name: "Marchena", score: 99, position: "Up", grade: "A" },
  { rank: 26, team_name: "Faroe", score: 99, position: "Down", grade: "A" },
  { rank: 27, team_name: "Flinders", score: 99, position: "Up", grade: "A" },
  { rank: 28, team_name: "Capraia", score: 99, position: "Down", grade: "A" },
  { rank: 29, team_name: "Fairholme", score: 99, position: "Up", grade: "A" },
  { rank: 30, team_name: "Amelia", score: 98, position: "Up", grade: "A" },
  { rank: 31, team_name: "Damien", score: 98, position: "Down", grade: "A" },
  { rank: 32, team_name: "Fiji", score: 98, position: "Down", grade: "A" },
  { rank: 33, team_name: "Ellesmere", score: 98, position: "Down", grade: "A" },
  { rank: 34, team_name: "Galapagos", score: 98, position: "Up", grade: "A" },
  { rank: 35, team_name: "Lastovo", score: 98, position: "Down", grade: "A" },
  { rank: 36, team_name: "Moreton", score: 98, position: "Down", grade: "A" },
  { rank: 37, team_name: "Adonara", score: 98, position: "Up", grade: "A" },
  { rank: 38, team_name: "Tenerive", score: 98, position: "Up", grade: "A" },
  { rank: 39, team_name: "Anambas", score: 98, position: "Up", grade: "A" },
  { rank: 40, team_name: "Haruku", score: 98, position: "Down", grade: "A" },
  { rank: 41, team_name: "Fyn", score: 98, position: "Up", grade: "A" },
  { rank: 42, team_name: "Devon", score: 97, position: "Down", grade: "A" },
  { rank: 43, team_name: "Lasia", score: 97, position: "Down", grade: "A" },
  { rank: 44, team_name: "Samosir", score: 97, position: "Up", grade: "A" },
  { rank: 45, team_name: "Somerset", score: 97, position: "Up", grade: "A" },
  { rank: 46, team_name: "Sudan", score: 97, position: "Up", grade: "A" },
  { rank: 47, team_name: "Crabera", score: 97, position: "Down", grade: "A" },
  { rank: 48, team_name: "Lembata", score: 97, position: "Down", grade: "A" },
  { rank: 49, team_name: "Graciosa", score: 96, position: "Down", grade: "A" },
  { rank: 50, team_name: "Luzon", score: 96, position: "Up", grade: "A" },
  { rank: 51, team_name: "Mindanao", score: 96, position: "Down", grade: "A" },
  { rank: 52, team_name: "Navarino", score: 96, position: "Up", grade: "A" },
  { rank: 53, team_name: "Amorgós", score: 96, position: "Up", grade: "A" },
  { rank: 54, team_name: "Ibiza", score: 96, position: "Down", grade: "A" },
  { rank: 55, team_name: "Bajau", score: 96, position: "Up", grade: "A" },
  { rank: 56, team_name: "Crete", score: 96, position: "Down", grade: "A" },
  { rank: 57, team_name: "Baffin", score: 95, position: "Up", grade: "A" },
  { rank: 58, team_name: "Bruny", score: 95, position: "Up", grade: "A" },
  { rank: 59, team_name: "Kálymnos", score: 95, position: "Down", grade: "A" },
  { rank: 60, team_name: "Hawaii", score: 95, position: "Down", grade: "A" },
  { rank: 61, team_name: "Corsica", score: 95, position: "Down", grade: "A" },
  { rank: 62, team_name: "Capri", score: 95, position: "Down", grade: "A" },
  { rank: 63, team_name: "Melville", score: 95, position: "Down", grade: "A" },
  { rank: 64, team_name: "Murano", score: 95, position: "Up", grade: "A" },
  { rank: 65, team_name: "Normandy", score: 95, position: "Down", grade: "A" },
  { rank: 66, team_name: "Balearic", score: 95, position: "Up", grade: "A" },
  { rank: 67, team_name: "Santorini", score: 95, position: "Up", grade: "A" },
  { rank: 68, team_name: "Embiez", score: 94, position: "Down", grade: "A" },
  { rank: 69, team_name: "Madeira", score: 94, position: "Down", grade: "A" },
  { rank: 70, team_name: "Maldives", score: 94, position: "Up", grade: "A" },
  { rank: 71, team_name: "Maui", score: 94, position: "Down", grade: "A" },
  { rank: 72, team_name: "Mersea", score: 94, position: "Down", grade: "A" },
  { rank: 73, team_name: "Foula", score: 94, position: "Down", grade: "A" },
  { rank: 74, team_name: "Samoa", score: 94, position: "Up", grade: "A" },
  { rank: 75, team_name: "Victoria", score: 93, position: "Down", grade: "A" },
  { rank: 76, team_name: "Palawan", score: 92, position: "Down", grade: "A" },
  { rank: 77, team_name: "Oleron", score: 92, position: "Down", grade: "A" },
  { rank: 78, team_name: "Osea", score: 92, position: "Down", grade: "A" },
  { rank: 79, team_name: "Tanzania", score: 91, position: "Down", grade: "A" },
  { rank: 80, team_name: "Britania", score: 91, position: "Down", grade: "A" },
  { rank: 81, team_name: "Tresco", score: 91, position: "Down", grade: "A" },
  { rank: 82, team_name: "Moorea", score: 90, position: "Down", grade: "A" },
  { rank: 83, team_name: "Norfolk", score: 90, position: "Down", grade: "A" },
  { rank: 84, team_name: "Tahiti", score: 89, position: "Up", grade: "A" },
  { rank: 85, team_name: "Rakata", score: 88, position: "Up", grade: "A" },
  { rank: 86, team_name: "Cabrera", score: 88, position: "Down", grade: "A" },
  { rank: 87, team_name: "Shikoku", score: 87, position: "Down", grade: "A" },
  { rank: 88, team_name: "Skye", score: 86, position: "Down", grade: "A" },
  { rank: 89, team_name: "Kuba", score: 86, position: "Down", grade: "A" },
  {
    rank: 90,
    team_name: "Pantelleria",
    score: 85,
    position: "Down",
    grade: "A",
  },
  { rank: 91, team_name: "Pianosa", score: 84, position: "Down", grade: "A" },
  { rank: 92, team_name: "Philae", score: 84, position: "Down", grade: "A" },
  { rank: 93, team_name: "Kárpatos", score: 84, position: "Down", grade: "A" },
  { rank: 94, team_name: "Baltra", score: 83, position: "Up", grade: "A" },
  { rank: 95, team_name: "Bengkalis", score: 83, position: "Up", grade: "A" },
  { rank: 96, team_name: "Teraina", score: 83, position: "Down", grade: "A" },
  { rank: 97, team_name: "Rhodes", score: 82, position: "Down", grade: "A" },
  { rank: 98, team_name: "Kauai", score: 81, position: "Down", grade: "A" },
  { rank: 99, team_name: "Torcello", score: 80, position: "Down", grade: "A" },
  { rank: 100, team_name: "Bennett", score: 80, position: "Down", grade: "A" },
];
